/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'karl' at '16.12.14 15:37' with Gradle 2.2.1
 *
 * @author karl, @date 16.12.14 15:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
